name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Der Branch, auf dem der Workflow laufen soll

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Empfohlene Node-Version für Vite

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Verwendet den neu erstellten dist-Ordner
          destination_dir: .   # Optional, aber hält den gh-pages-Branch sauber
